### ISSUE TITLE
problems about poison in main.py

### ISSUE THREAD

**Issue by zqtshuaibi** [Gwinhen/BackdoorVault#2]
if  args.attack == 'dfst_detox' 
i can't find where  you use the unet you save in detox when you train the model
can you explain it ?

**Comment by Gwinhen** [comment]
At line 181 in `attack.py`, it calls the backdoor injection function of DFST, which is implemented in `backdoors/dfst.py` (using the unet).

Please let me know whether this answers your question.

**Comment by zqtshuaibi** [comment]
i ignore this....,thanks for you answer!  It has solved my doubts
